---
name: CI/CD Tests # name of workflow
on: [pull_request] # run on pull request
jobs:
  Setup: # name of job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    # checkout repository (if pull request; merge branch to main temporarily for testing purposes)

    - name: Install Python 3.10
      uses: actions/setup-python@v4    # install python 3.10
      with:
        python-version: '3.10'
