---
name: CI/CD Tests # name of workflow
on: [pull_request] # run on pull request
jobs:
  Setup: # name of job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3    # checkout repository

    - name: Install Python 3.10
      uses: actions/setup-python@v4    # install python 3.10
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: make install_dependencies # use Makefile command to install dependencies

    - name: Run Precommit
      run: |
        source venv/bin/activate # need to activate venv before running
        make run_precommit # use Makefile command to run precommit on ALL files
